server:
    servlet:
        encoding:
            charset: UTF-8
            force: true

spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/testdb;
        username: sa
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                show_sql: true
                format_sql: true
logging:
    level:
        org.hibernate.sql: debug